apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
{{ include "labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.deployment.listenPort }}
      targetPort: {{ .Values.deployment.listenPort }}
      protocol: TCP
  selector:
{{ include "selectorLabels" . | indent 4 }}
